/**
 * SEO Configuration
 * Centralized SEO data to avoid redundancy across the application
 * All SEO-related metadata should be imported from here
 */

// Site configuration - used in robots.ts, sitemap.ts, and metadata
export const SITE_CONFIG = {
  name: "Jean Paul Elisa",
  fullName: "Jean Paul Elisa NIYOKWIZERWA",
  title: "Tech Lead & Software Engineer | Entrepreneur",
  url: "https://www.ndevuspace.com",
  locale: "en_US",
  description: {
    short:
      "Tech Lead, Full Stack Software Engineer & Entrepreneur specializing in React, Node.js, TypeScript, Python, and AI/ML. Based in Kigali, Rwanda.",
    long: "Jean Paul Elisa NIYOKWIZERWA - Tech Lead, Full Stack Software Engineer & Entrepreneur based in Kigali, Rwanda. ALX Graduate & Stanford ML certified. Specializing in React, Node.js, TypeScript, Python, Django, and AI/ML. Building scalable products, leading engineering teams, and mentoring developers across East Africa.",
    tagline:
      "Building robust, scalable applications that deliver exceptional user experiences",
  },
  location: {
    city: "Kigali",
    country: "Rwanda",
    region: "East Africa",
  },
  images: {
    profile: "/images/my-profile-pc.jpeg",
    ogImage: "/opengraph-image", // Auto-generated by Next.js
  },
};

// SEO Keywords - Comprehensive coverage for various search queries
export const SEO_KEYWORDS = [
  // Personal branding
  "Jean Paul Elisa",
  "Jean Paul Elisa NIYOKWIZERWA",
  "Niyokwizerwa Jean Paul Elisa",
  "Jean Paul Niyokwizerwa",
  "Ndevu",
  "Ndevu Space",
  "Ndevuspace",
  "Ndevu12",
  "Jean Paul Elisa Resume",
  "Jean Paul Elisa CV",
  "Jean Paul Elisa Portfolio",

  // Job titles - General
  "Software Engineer",
  "Full Stack Developer",
  "Full Stack Engineer",
  "Tech Lead",
  "Technical Lead",
  "Engineering Lead",
  "Senior Software Engineer",
  "Senior Developer",
  "Web Developer",
  "Frontend Developer",
  "Backend Developer",
  "Software Developer",

  // Job titles - Specialized
  "React Developer",
  "Node.js Developer",
  "TypeScript Developer",
  "Python Developer",
  "Next.js Developer",
  "JavaScript Developer",
  "Django Developer",
  "FastAPI Developer",
  "REST API Developer",
  "Cloud Developer",
  "DevOps Engineer",

  // AI/ML specific
  "AI Engineer",
  "ML Engineer",
  "Machine Learning Engineer",
  "AI Developer",
  "AI/ML Developer",
  "Artificial Intelligence Engineer",
  "Deep Learning Engineer",
  "TensorFlow Developer",
  "Python AI Developer",

  // Rwanda specific
  "Developer Rwanda",
  "Software Engineer Rwanda",
  "Web Developer Rwanda",
  "Full Stack Developer Rwanda",
  "Tech Lead Rwanda",
  "AI Engineer Rwanda",
  "ML Engineer Rwanda",
  "Python Developer Rwanda",
  "React Developer Rwanda",
  "Kigali Developer",
  "Kigali Software Engineer",
  "Kigali Tech Lead",
  "Rwanda Programmer",
  "Rwanda Coder",
  "Hire Developer Rwanda",

  // East Africa specific
  "Developer East Africa",
  "Software Engineer East Africa",
  "Web Developer East Africa",
  "Full Stack Developer East Africa",
  "Tech Lead East Africa",
  "AI Engineer East Africa",
  "ML Engineer East Africa",
  "East African Developer",
  "East Africa Programmer",

  // Africa specific
  "Developer Africa",
  "Software Engineer Africa",
  "Web Developer Africa",
  "Full Stack Developer Africa",
  "Tech Lead Africa",
  "AI Engineer Africa",
  "ML Engineer Africa",
  "African Developer",
  "African Software Engineer",
  "African Tech Talent",
  "Hire Developer Africa",

  // Industry terms
  "Web Development",
  "Software Development",
  "Application Development",
  "Web Applications",
  "SaaS Developer",
  "Startup Developer",
  "Freelance Developer",
  "Remote Developer",
  "Remote Software Engineer",

  // Technology stacks
  "MERN Stack Developer",
  "PERN Stack Developer",
  "JavaScript Full Stack",
  "TypeScript Full Stack",
  "React Node Developer",
  "PostgreSQL Developer",
  "MongoDB Developer",
  "Docker Developer",
  "AWS Developer",
  "Cloud Engineer",

  // Entrepreneurial
  "Tech Entrepreneur",
  "Tech Entrepreneur Rwanda",
  "Tech Entrepreneur Africa",
  "Startup Founder",
  "Startup Founder Rwanda",
  "Tech Startup Founder",
  "Tech Co-founder",
  "Technical Co-founder",
  "Technical Co-founder Rwanda",
  "Technical Co-founder Africa",
  "Tech Founder East Africa",
  "African Tech Entrepreneur",
  "Rwandan Entrepreneur",
  "Product Builder",
  "SaaS Founder",
  "Digital Entrepreneur",
  "Tech Innovator Rwanda",
  "Tech Innovator Africa",
  "Business Technology Leader",
  "Tech Business Owner",

  // Educational / Mentorship
  "Tech Mentor",
  "Tech Mentor Rwanda",
  "Tech Mentor Africa",
  "Coding Mentor",
  "Software Engineering Mentor",
  "Programming Tutor Rwanda",
  "Tech Educator",
  "Tech Educator Africa",
  "Software Development Trainer",
  "Web Development Instructor",
  "ALX Graduate",
  "ALX Software Engineer",
  "Stanford ML Certificate",
  "University of Rwanda Graduate",
  "Rwanda Tech Graduate",
  "Tech Speaker Rwanda",
  "Tech Speaker Africa",
  "Developer Community Rwanda",
  "Tech Community Leader",
  "Open Source Contributor",
  "GitHub Developer Rwanda",

  // DSA Coaching / Interview Prep
  "DSA Coach",
  "DSA Coach Rwanda",
  "DSA Coach Africa",
  "DSA Mentor",
  "DSA Tutor",
  "Data Structures Coach",
  "Algorithms Coach",
  "Data Structures and Algorithms Mentor",
  "DSA Interview Prep",
  "DSA Interview Coach",
  "Coding Interview Coach",
  "Coding Interview Prep Rwanda",
  "Coding Interview Mentor",
  "Technical Interview Coach",
  "Technical Interview Prep Africa",
  "LeetCode Coach",
  "LeetCode Mentor Rwanda",
  "Competitive Programming Coach",
  "Competitive Programming Mentor",
  "Problem Solving Coach",
  "Algorithm Tutor Rwanda",
  "Algorithm Tutor Africa",
  "DSA Training Rwanda",
  "DSA Training Africa",
  "Software Interview Preparation",
  "FAANG Interview Prep",
  "Big Tech Interview Coach",
];

// Social profiles for JSON-LD sameAs (public URLs only)
// These are intentionally public for SEO - they link to your public profiles
export const SOCIAL_PROFILES = {
  github: "https://github.com/Ndevu12",
  linkedin: "https://linkedin.com/in/niyokwizerwa-jean-paul-elisa",
  // Twitter handle for cards (without @)
  twitterHandle: "ndevu12",
};

// Skills/expertise for JSON-LD knowsAbout
export const EXPERTISE_AREAS = [
  // Technical
  "Web Development",
  "Full Stack Development",
  "Frontend Development",
  "Backend Development",
  "React",
  "Node.js",
  "TypeScript",
  "JavaScript",
  "Python",
  "Django",
  "FastAPI",
  "Next.js",
  "PostgreSQL",
  "MongoDB",
  "Docker",
  "AWS",
  "Machine Learning",
  "Artificial Intelligence",
  "TensorFlow",
  "REST API Development",
  "Cloud Computing",
  "DevOps",
  // Leadership & Business
  "Technical Leadership",
  "Team Management",
  "Product Development",
  "Entrepreneurship",
  "Startup Development",
  "Business Strategy",
  "Tech Mentorship",
  "Software Architecture",
];

// Tech stack for OG image display (top 5)
export const FEATURED_TECH = ["React", "Node.js", "TypeScript", "Next.js", "Python"];

// Pages for sitemap - IMPORTANT: Only include actual indexable pages
// Hash URLs (/#about, etc.) are NOT indexable by search engines and waste crawl budget
export const SITE_PAGES = [
  { path: "", priority: 1.0, changeFreq: "weekly" as const },
  { path: "/cv", priority: 0.9, changeFreq: "monthly" as const },
];

// Disallowed paths for robots.txt (internal/private routes)
export const DISALLOWED_PATHS = ["/api/", "/admin/", "/_next/", "/private/"];

/**
 * Generate JSON-LD Person Schema
 */
export function getPersonSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "Person",
    name: SITE_CONFIG.fullName,
    alternateName: SITE_CONFIG.name,
    url: SITE_CONFIG.url,
    image: `${SITE_CONFIG.url}${SITE_CONFIG.images.profile}`,
    jobTitle: SITE_CONFIG.title,
    description: SITE_CONFIG.description.short,
    address: {
      "@type": "PostalAddress",
      addressLocality: SITE_CONFIG.location.city,
      addressCountry: SITE_CONFIG.location.country,
    },
    sameAs: [SOCIAL_PROFILES.github, SOCIAL_PROFILES.linkedin],
    knowsAbout: EXPERTISE_AREAS,
  };
}

/**
 * Generate JSON-LD WebSite Schema
 */
export function getWebsiteSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: `${SITE_CONFIG.name} - Portfolio`,
    url: SITE_CONFIG.url,
    description: `Portfolio of ${SITE_CONFIG.name} - ${SITE_CONFIG.title}`,
    author: {
      "@type": "Person",
      name: SITE_CONFIG.fullName,
    },
  };
}
